package(
  default_visibility=["//visibility:public"]
)

alias (
  name = "jsonnet",
  actual = "@io_google_jsonnet//cmd:jsonnet"
)

alias (
  name = "jsonnetfmt",
  actual = "@io_google_jsonnet//cmd:jsonnetfmt"
)
