version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: luscoma/shortner:latest
    deploy:
      replicas: 5
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
      - "4001:8080"
    networks:
      - webnet
  redis:
   image: redis
   ports:
     - "6379:6379"
   volumes:
     - "/c/Temp/data2:/data2"
   command: redis-server --appendonly yes
   networks:
     - webnet 
networks:
  webnet:
