apiVersion: certmanager.k8s.io/v1alpha1
kind: Issuer
metadata:
  name: test-selfsigned
spec:
  selfSigned: {}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: selfsigned-cert
spec:
  commonName: whut.page
  secretName: selfsigned-cert-tls
  issuerRef:
    name: test-selfsigned
